from setuptools import setup, find_packages

setup(
    name="localclaw",
    version="1.0.0",
    description="MARK XXXV - Next-Generation Personal AI Assistant",
    long_description=open("README.md", encoding="utf-8").read(),
    long_description_content_type="text/markdown",
    author="JARVIS Systems",
    url="https://github.com/JARVIS-Systems/Mark-XXXV",
    packages=find_packages(),
    include_package_data=True,
    python_requires=">=3.11",
    install_requires=[
        "sounddevice>=0.5.1",
        "google-genai>=1.0.0",
        "google-generativeai>=0.8.0",
        "pillow>=11.0.0",
        "requests>=2.32.0",
        "beautifulsoup4>=4.12.0",
        "duckduckgo-search>=7.0.0",
        "playwright>=1.50.0",
        "pyautogui>=0.9.54",
        "pyperclip>=1.9.0",
        "pygetwindow>=0.0.9",
        "opencv-python>=4.10.0",
        "numpy>=2.0.0",
        "mss>=10.0.0",
        "psutil>=6.1.0",
        "comtypes>=1.4.0",
        "pycaw>=20240210",
        "win10toast>=0.9",
        "send2trash>=1.8.0",
        "youtube-transcript-api>=0.6.0",
        "pywinauto>=0.6.8",
        "python-dotenv>=1.0.0",
    ],
    entry_points={
        "console_scripts": [
            "jarvis=main:main",
        ],
    },
    classifiers=[
        "Development Status :: 4 - Beta",
        "Intended Audience :: End Users/Desktop",
        "License :: Free for Non-Commercial Use",
        "Operating System :: Microsoft :: Windows",
        "Programming Language :: Python :: 3",
        "Programming Language :: Python :: 3.11",
        "Programming Language :: Python :: 3.12",
        "Topic :: Scientific/Engineering :: Artificial Intelligence",
    ],
)
